name: magic_insta
description: "A project where user can download IG posts"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flex_color_scheme: ^8.1.1
  pretty_dio_logger: ^1.4.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  permission_handler: ^11.4.0
  gap: ^3.0.1
  chewie: ^1.11.1
  video_player: ^2.9.5
  firebase_core: ^3.13.0
  path_provider: ^2.1.5
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  background_downloader: ^9.2.0
  add_to_gallery: ^0.4.0+1
  device_info_plus: ^11.3.3
  unity_ads_plugin: ^0.3.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
