// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaI3SjVA77016N5xXaKWms5_45yChpa1g',
    appId: '1:714081474117:web:d56db5dd8983a81c6c352c',
    messagingSenderId: '714081474117',
    projectId: 'magicinsta-9999',
    authDomain: 'magicinsta-9999.firebaseapp.com',
    storageBucket: 'magicinsta-9999.firebasestorage.app',
    measurementId: 'G-CEMYR5TDGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfYngnHkXjR1EmduGpnidgnnqUFEQyT1g',
    appId: '1:714081474117:android:533e74694a1646d86c352c',
    messagingSenderId: '714081474117',
    projectId: 'magicinsta-9999',
    storageBucket: 'magicinsta-9999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-SsgVMQ4rfcU8OT-MZ9BsgwINvkeP-t8',
    appId: '1:714081474117:ios:b8ed8abb61790d2a6c352c',
    messagingSenderId: '714081474117',
    projectId: 'magicinsta-9999',
    storageBucket: 'magicinsta-9999.firebasestorage.app',
    androidClientId: '714081474117-4j8jejnsrn31ie0vptpcl6h7rpmspbls.apps.googleusercontent.com',
    iosClientId: '714081474117-nqts0c5ndqlb8p3lcakhk1etg8s3j2ad.apps.googleusercontent.com',
    iosBundleId: 'com.himanshu.magicInsta',
  );

}